"""HMAC-signed confirmation tokens for the source-size confirmation flow (m5e).

When a POST /api/documents request reports a source size between the soft cap
(``IngestConfig.max_source_bytes``, default 200 MB) and the hard cap
(``IngestConfig.max_source_bytes_hard``, default 5 GB), the route returns
HTTP 413 with a body containing a token issued by ``issue_token``. The caller
re-submits the same request with ``confirmation_token`` in the body; the
server calls ``validate_token`` and proceeds with the ingest if the token
is VALID.

Token shape: ``<payload-b64url>.<sig-b64url>`` where ``sig`` is
HMAC-SHA256(secret, payload-bytes) and ``payload`` is JSON
``{"v": 1, "uri": <str>, "size": <int>, "size_precise": <bool>, "exp": <unix-int>}``.

Stateless by design — there is no in-memory store of issued tokens; HMAC
verification is the only check beyond TTL and URI binding.

Single-worker invariant (m5e §11.A.2): the per-process HMAC secret is
regenerated by ``configure_confirmation()`` at lifespan startup. This is
correct for the current architecture (Dockerfile CMD ``['ariadne-core',
'serve']`` + ``__main__.py`` ``uvicorn.Server`` + ``asyncio.run(server.serve())``,
which is single-process). If multi-worker uvicorn is ever introduced, cross-
worker secret coordination is part of that future ticket scope, not this one.
A container restart invalidates in-flight tokens; the caller path is
identical to ``EXPIRED`` (re-submit gets a fresh 413 with a new token).

Stdlib-only: ``hmac``, ``hashlib``, ``base64``, ``json``, ``secrets``, ``time``.
"""
from __future__ import annotations

import base64
import hmac
import json
import logging
import secrets
import time
from enum import Enum
from hashlib import sha256
from typing import Optional

logger = logging.getLogger(__name__)

# Per-process HMAC secret; populated by ``configure_confirmation()`` from the
# FastAPI lifespan. Tests override via ``configure_confirmation(secret=...)``.
_CONFIRMATION_SECRET: Optional[bytes] = None

# Token version — bump if the payload schema changes.
_TOKEN_VERSION = 1


class ValidationResult(Enum):
    """Tagged result of ``validate_token``.

    VALID — HMAC verifies, payload well-formed, ``exp`` in the future, URI matches.
    EXPIRED — HMAC verifies but ``time.time() >= exp``.
    TAMPERED — payload malformed, HMAC mismatch, missing required fields, or
        unsupported version.
    URI_MISMATCH — payload's signed URI does not match the URI of the
        re-submitted request.
    """

    VALID = "valid"
    EXPIRED = "expired"
    TAMPERED = "tampered"
    URI_MISMATCH = "uri_mismatch"


def configure_confirmation(secret: Optional[bytes] = None) -> None:
    """Install the per-process HMAC secret. Called from app.py lifespan.

    Pass ``secret=None`` (default) to generate a fresh 32-byte random secret
    via ``secrets.token_bytes(32)``. Tests override with a deterministic
    value via the autouse ``_confirmation_secret_isolation`` fixture in
    ``tests/conftest.py``.
    """
    global _CONFIRMATION_SECRET
    if secret is None:
        secret = secrets.token_bytes(32)
    _CONFIRMATION_SECRET = secret
    logger.info(
        "confirmation-secret: per-process-regenerated "
        "(in-flight tokens will not survive restart)"
    )


def _b64url_encode(data: bytes) -> str:
    """Base64url-encode without padding (the ``.`` separator is unambiguous)."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64url_decode(data: str) -> bytes:
    """Base64url-decode, restoring padding as needed."""
    pad = "=" * ((4 - len(data) % 4) % 4)
    return base64.urlsafe_b64decode(data + pad)


def issue_token(
    *,
    source_uri: str,
    reported_size: int,
    size_precise: bool,
    ttl_seconds: int,
) -> tuple[str, int]:
    """Issue an HMAC-signed confirmation token.

    Args:
        source_uri: The URI the operator is being asked to confirm. Signed into
            the token; ``validate_token`` rejects re-submissions with a different
            URI (URI_MISMATCH).
        reported_size: Size observed at probe time. Forensic only after
            rev2 risk-1 pick 1a — the validate path no longer reads it.
        size_precise: True if ``reported_size`` came from a HEAD response with
            Content-Length; False if it came from a chunked-read overrun
            (i.e., "we observed at least ``reported_size`` bytes before
            stopping"). Forensic only at validate-time; surfaced for forward-
            compat with future size-correlation logging.
        ttl_seconds: Token validity window in seconds; the payload's ``exp``
            is ``int(time.time()) + ttl_seconds``.

    Returns:
        ``(token, expires_at_unix)`` — token is a string of the form
        ``<payload-b64url>.<sig-b64url>``; ``expires_at_unix`` is an int
        suitable for the wire response's ``ttl_seconds`` framing.

    Raises:
        RuntimeError: if ``configure_confirmation`` has not yet been called
        (the per-process secret is None).
    """
    if _CONFIRMATION_SECRET is None:
        raise RuntimeError(
            "confirmation secret not configured; "
            "call configure_confirmation() at app startup"
        )
    expires_at = int(time.time()) + ttl_seconds
    payload = {
        "v": _TOKEN_VERSION,
        "uri": source_uri,
        "size": int(reported_size),
        "size_precise": bool(size_precise),
        "exp": expires_at,
    }
    payload_bytes = json.dumps(
        payload, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")
    sig = hmac.new(_CONFIRMATION_SECRET, payload_bytes, sha256).digest()
    token = f"{_b64url_encode(payload_bytes)}.{_b64url_encode(sig)}"
    return token, expires_at


def validate_token(token: str, *, source_uri: str) -> ValidationResult:
    """Constant-time HMAC verify + ``exp`` check + URI match.

    Returns a tagged ``ValidationResult``. Size is NOT validated (m5e rev2
    risk-1 pick 1a) — the token's ``size`` and ``size_precise`` fields are
    forensic, recorded for operator-log correlation only. The actual
    memory-safety bound on the post-validate fetch is the chunked-read
    accumulator gated at ``effective_hard``, which still aborts a fetch
    whose actual size grows above the hard cap regardless of what the
    token says.

    Validation order (any failure short-circuits):

      1. Parse the dot-split.  Malformed → TAMPERED.
      2. Compute HMAC; constant-time compare.  Mismatch → TAMPERED.
      3. Decode JSON and check required fields + version.
         Missing fields, wrong types, or ``v != 1`` → TAMPERED.
         Missing ``size_precise`` → defaults to True (default-permissive,
         pinned at rev3 §11.A.6 / Nit 6 — see module docstring).
      4. ``time.time() >= exp`` → EXPIRED.
      5. ``payload.uri != submitted_uri`` → URI_MISMATCH.
      6. All checks pass → VALID.
    """
    if _CONFIRMATION_SECRET is None:
        # Defensive: if validate is somehow called before configure, treat
        # every token as TAMPERED rather than raising.
        return ValidationResult.TAMPERED

    # 1. Parse the dot-split.
    if not isinstance(token, str) or token.count(".") != 1:
        return ValidationResult.TAMPERED
    payload_part, sig_part = token.split(".", 1)
    try:
        payload_bytes = _b64url_decode(payload_part)
        sig_bytes = _b64url_decode(sig_part)
    except (ValueError, base64.binascii.Error):
        return ValidationResult.TAMPERED

    # 2. Compute HMAC; constant-time compare.
    expected_sig = hmac.new(
        _CONFIRMATION_SECRET, payload_bytes, sha256
    ).digest()
    if not hmac.compare_digest(expected_sig, sig_bytes):
        return ValidationResult.TAMPERED

    # 3. Decode JSON and check required fields + version.
    try:
        payload = json.loads(payload_bytes.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError):
        return ValidationResult.TAMPERED
    if not isinstance(payload, dict):
        return ValidationResult.TAMPERED
    if payload.get("v") != _TOKEN_VERSION:
        return ValidationResult.TAMPERED
    if not isinstance(payload.get("uri"), str):
        return ValidationResult.TAMPERED
    if not isinstance(payload.get("size"), int) or isinstance(
        payload.get("size"), bool
    ):
        # ``isinstance(True, int)`` is True in Python; reject bools explicitly.
        return ValidationResult.TAMPERED
    if not isinstance(payload.get("exp"), int) or isinstance(
        payload.get("exp"), bool
    ):
        return ValidationResult.TAMPERED
    # ``size_precise`` is optional: a missing field defaults to True
    # (default-permissive, pinned for forward-compat — see module docstring).
    if "size_precise" in payload and not isinstance(
        payload["size_precise"], bool
    ):
        return ValidationResult.TAMPERED

    # 4. exp check.
    if time.time() >= payload["exp"]:
        return ValidationResult.EXPIRED

    # 5. URI match.
    if payload["uri"] != source_uri:
        return ValidationResult.URI_MISMATCH

    return ValidationResult.VALID
